import {getRepository, MigrationInterface, QueryRunner, Table} from "typeorm";

export class ingredients1624211228235 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Fillet','kg',7000,62,12)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Sauce fillet','kg',2500,69,24)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('chicken breast','kg',1800,56,26)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('baguette','loaf',60,46,24)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('steak','kg',1000,42,20)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('salt','kg',100,50,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('flour','kg',375,61,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('egg','egg',42,50,24)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('bread crumbs','kg',700,48,19)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('lemon','kg',400,52,17)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('ketchup','kg',800,47,21)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('mayonnaise','kg',800,64,27)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('kashkaval','kg',2750,43,11)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('turkey roast','kg',8000,64,21)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('boiled mushrooms','kg',3000,50,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('vegetable oil','kg',1000,47,22)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('marinated chicken breast','kg',2000,65,18)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('marinara sauce','kg',3000,68,15)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('entercoute veal','kg',15000,50,15)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('balck pepper','kg',3000,56,17)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('dried onion','kg',300,54,24)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('fresh mushroom','kg',2200,63,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('soya sauce','kg',3400,57,30)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('barbecue sauce','kg',3500,58,25)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('vienna bread','loaf',100,41,28)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('cucumber pickels','kg',500,57,12)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Arabic lettuce','bundle',175,57,23)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('tomato','kg',400,53,14)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Beef taco filling','kg',14000,49,24)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('tortilla bread','loaf',120,54,12)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('sour cream','bottle',2500,62,18)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('green onions','bundle',150,48,12)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('coriander','bundle',100,52,11)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('powdered onion','kg',3000,45,12)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Chicken taco filling','kg',13000,50,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('grouper fish','kg',3000,43,20)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Bugrer beef','kg',5000,48,28)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('western lettuce','piece',150,65,25)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('burger bread','loaf',100,58,24)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('argula','bundle',60,42,13)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('lollo rosso lettuce','piece',150,43,28)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('cherry tomato','kg',1200,48,19)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('chiken soya sauce','kg',2800,42,20)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('white bread','bundle',350,50,25)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('sujuk meat','kg',3000,56,23)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('pickled turnip','kg',400,60,13)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('smoken turkey','pack',1100,50,26)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('mozarella','kg',2700,54,29)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('calamari','kg',20000,41,25)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('chopped onion','kg',500,58,21)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('tanboura dough','kg',1000,42,27)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('fresh potato','kg',500,53,26)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('cocktail sauce','kg',2000,50,15)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('pesto','kg',3500,46,15)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('oregano','kg',2500,40,25)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('olive oil','kg',1975,68,18)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Macaroni Chips','piece',2500,55,22)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('animal butter','kg',5500,68,20)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('parsley','kg',150,60,23)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('tarragon','kg',100,48,12)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Thyme','kg',150,56,12)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('spinach','kg',100,61,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('westchester sauce','kg',3500,66,11)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('demiglace sauce','kg',1500,40,22)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('maggie','kg',1200,58,27)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('fresh cream','kg',2200,56,28)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('rice','kg',1200,67,26)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('ghee','kg',2600,49,16)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('peeled garlic','kg',3000,45,24)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('cardamom seeds','kg',31000,42,30)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('bay leaves','kg',1300,42,12)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('ground ginger','kg',2500,68,21)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('white pepper','kg',4500,42,18)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('balsamic sauce','kg',4500,58,30)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('rose mary','kg',1700,42,22)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('powdered gralic','kg',2450,65,13)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Creamy white garlic sauce','kg',1000,63,29)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Frozen potato','kg',1200,68,27)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Papprika','kg',2500,69,16)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('honey','kg',3500,57,23)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('tabasco','bottle',200,65,22)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('finely ground beef','kg',6500,40,23)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('parmesan','kg',11500,65,17)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Milk','kg',3300,55,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('cooking cream','kg',2400,61,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('labneh','kg',1200,59,14)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('lemon juice','kg',1200,58,18)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('red pepper','kg',500,40,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('green pepper','kg',500,60,15)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('diced tomato','kg',500,66,21)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('hot pepper','kg',700,48,18)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('corn','kg',1300,64,17)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('red kidney beans','kg',2000,68,18)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('dried coriander','kg',1300,47,12)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('powdered cumin','kg',2700,55,26)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('toast','kg',1200,67,13)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('panini  bread','kg',1500,59,19)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('sheep''s tail fat','kg',2000,44,26)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Pesto Barilla','pack',1500,60,27)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('groats','kg',600,65,24)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('black lentils','kg',600,67,11)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('mustard seeds','kg',2500,48,14)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('corn flour','kg',480,67,25)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('baking poweder','kg',1500,48,11)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('chinese salt','kg',1500,70,19)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('yeast','kg',2000,70,20)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('coarse sugar','kg',360,55,18)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('veal backs','kg',6800,53,24)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Nutmeg','kg',4800,50,28)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('powedered curry','kg',2100,52,22)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('pepper molasses','kg',2000,46,28)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('chef''s spices','kg',400,42,17)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('powdered cinnamon','kg',3500,59,18)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('cucumber','kg',375,55,11)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('carrot','kg',250,69,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('zuchini','kg',350,49,21)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('eggplant','kg',300,69,26)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('cauliflower','kg',350,54,29)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('potato','kg',445,49,16)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('green mint','kg',60,50,30)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Common Purslane','bundle',60,56,25)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Radish','bundle',100,62,11)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('green thyme','kg',1500,56,21)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('beet','kg',250,54,18)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('green cabbage','kg',275,67,22)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Green beans','kg',800,65,28)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('green okra','kg',1000,70,21)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Freekeh','kg',1300,58,30)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('sheept meat','kg',6000,41,28)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('peas','kg',1300,63,19)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('basmati rice','kg',1100,65,15)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('beryani spices','kg',2400,53,23)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('chicken thighs','kg',2000,62,28)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('kabseh spices','kg',2200,65,26)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('bean sprouts','kg',10000,58,28)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('asparagus','piece',3000,64,27)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('noodles','kg',500,49,25)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('coffee','kg',5000,52,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('espresso','kg',6600,47,29)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Monin sauce','bottle',7500,49,23)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('whipped cream','pack',2400,55,25)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('kiwi','kg',2500,66,19)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('pinapple juice','bottle',675,70,16)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('pinapple compote','pack',1600,64,17)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('orange','kg',225,50,19)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('frozen berries','kg',1200,41,15)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('apple pie','piece',2000,56,12)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('nescafe 3 in1','pack',40,49,21)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('chocolate ice cream','kg',1200,44,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('vanilla ice cream','kg',900,65,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('zohourat','pack',40,58,17)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('tea bag','pack',25,61,16)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('banana','kg',1300,44,20)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('frozen strawberry','kg',725,47,13)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Blossom water','bottle',1300,46,22)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Twix','piece',300,54,29)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('zohourat melissa','pack',40,68,14)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('zohourat anise','pack',40,61,28)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('zohourat thyme','pack',40,49,27)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('vanilla syrup','bottle',7000,41,23)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('sahlab','pack',3500,70,27)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('biscuit romba','pack',100,55,12)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('peach syrup','bottle',7000,69,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('strawberry syrup','bottle',7000,65,11)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('blue curacao syrup','bottle',7000,64,20)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('mandarine','bottle',250,44,22)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('marshmallow','pack',1500,41,13)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('frappe poweder','pack',3000,65,15)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('orange syrup','bottle',7000,45,30)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('cinnamon sticks','kg',4000,41,18)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('mango compote','pack',4500,41,28)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('oats','kg',2000,63,13)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('dates','kg',3000,70,21)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('persimmon','kg',700,54,29)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('nutella','pack',7500,51,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('apple','kg',1000,41,17)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('watermelon','kg',700,50,29)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('melon','kg',800,54,13)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('avocado','piece',1000,57,11)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('passion fruit syrup','bottle',7000,67,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('coffee filter','piece',100,49,27)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('nestle','pack',2000,58,28)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('grape syrup','bottle',7000,64,20)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('yogurt','kg',350,59,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('dried chickpeas','kg',600,47,18)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('carbonate','kg',1000,45,21)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('falfel spices','kg',3000,69,15)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('chicken sausage','kg',2200,47,19)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('gounded chicken','kg',1500,44,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('sumac','kg',1500,55,29)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('pomgrana hone','bottle',2000,46,11)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('pomegranate','kg',750,49,15)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('tahini','pack',3000,42,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('walnut','kg',7000,52,11)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Hot sauce','bottle',1500,66,26)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('sweet sauce','bottle',1500,48,13)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('dried mint','kg',1000,50,15)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('frozen broad bean','kg',1800,56,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('Tamrind','pack',1250,60,26)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('diced olives','kg',1200,57,24)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('powedered chickpeas','kg',1050,43,19)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('cornstarch','kg',2750,65,13)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('sesame oil','bottle',4000,42,10)");
await queryRunner.query("INSERT INTO ingredients(name,measurment,price,quantity,minthreshold) VALUES ('cheddar cheese','kg',7000,65,19)");

    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
